services:
  - type: web
    name: campus-connect-api-team-04
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
